name: setup xcode
run-name: prepare to setup xcode
on: [workflow_dispatch]
jobs:
  setup-xcode:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - run: /usr/bin/xcodebuild -version
